# Generated by Django 5.2 on 2025-04-25 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=110, verbose_name='Пункт меню')),
                ('slug', models.SlugField(max_length=110, unique=True, verbose_name='URL')),
                ('test_field', models.CharField(max_length=20)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='app_tree_menu.menuitem', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Элементы меню',
                'verbose_name_plural': 'Элементы меню',
            },
        ),
    ]
