# Generated by Django 5.2 on 2025-04-25 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tree_menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='test_field',
        ),
    ]
